build:
  only:
    refs:
      - master
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  only:
    refs:
      - master
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$PROD_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -zr --perms --chmod=u=xrw,go=xr ./dist/* madex@do.madex.pro:/var/www/iguru.hmns.ru/public_html